// This file is automatically generated. Do not edit it directly.
/**
 * @deprecated Supabase is no longer used. Authentication is now handled by the backend API.
 * See frontend/src/lib/mockAuth.ts for current auth implementation.
 */

export const supabase = null;
