# DataQuality/dbt_project.yml
name: data_quality
version: "1.0.0"
config-version: 2

profile: data_quality

model-paths: ["models"]
test-paths:  ["tests"]
seed-paths:  ["seeds"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  data_quality:
    staging:
      +materialized: view