name: 'data_prep_dbt'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_prep_dbt:
    +materialized: view

